name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test ./...
