name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      datastore:
        image: google/cloud-sdk
        ports:
          - 8000:8000
        options: -ti

    env:
      GO111MODULE: on
      DATASTORE_EMULATOR_HOST: 127.0.0.1:8000

    steps:
      - name: Start datastore emulator
        run: docker exec -d $(docker ps -f "ancestor=google/cloud-sdk" -q) gcloud beta emulators datastore start --project=pname --host-port 0.0.0.0:8000 --no-store-on-disk

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test -v ./... -tags="emulator"
